---
- hosts: armpit
  remote_user: root
  vars:
    mongodbrepodef: |
      [mongodb]
      name=MongoDB repo
      baseurl=http://downloads-distro.mongodb.org/repo/redhat/os/x86_64/
      gpgcheck=0
      enabled=1
  tasks:
    - name: Remove PHP 5.4
      yum:
        name: "{{ item }}"
        state: absent
      with_items:
        - php
        - php-mysql
        - php-fpm
        - php-pecl-mongo
    - name: Add the Remi PHP Repo
      yum: 
        name: http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
        state: present
    - name: Enable the Remi Base Repo
      ini_file: dest=/etc/yum.repos.d/remi.repo section=remi option=enabled value=1
    - name: Enable the Remi PHP 5.6 Repo
      ini_file: dest=/etc/yum.repos.d/remi.repo section=remi-php56 option=enabled value=1
    - name: Install basic build packages
      yum: 
        name: "{{ item }}"
        state: latest
      with_items:
        - epel-release
        - nodejs
        - npm
        - git
        - php
        - php-mysql
        - php-fpm
        - mongodb
        - mongodb-server
        - php-pecl-mongo
        - ruby
        - ruby-devel
        - rubygems
        - rpm-build
    - name: Ensure the fpm gem installed
      command: gem install fpm
    - name: Install composer
      shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      args:
        creates: /usr/local/bin/composer        
    - name: PHP phar.readonly turned Off
      ini_file: dest=/etc/php.ini section=Phar option=phar.readonly value=Off
    - name: Build the package
      shell: "{{ item }}"
      become: yes
      become_user: "{{ remote_user }}"   
      args:
        chdir: /vagrant
      with_items:
        - "composer config --global github-oauth.github.com {{ githubOauth }}"
        - npm install
        - node_modules/grunt-cli/bin/grunt buildrpm
      register: fpmresult
    - debug: var=fpmresult
    - name: copy RPM to tmp
      copy: 
        src: "{{ item }}"
        dest: /tmp
      with_fileglob:
        - deploy/*.rpm
      register: copiedrpms
    - debug: var=copiedrpms.results[0].dest
    - name: install armpit rpm from a local file
      yum: 
        name: "{{ copiedrpms.results[0].dest }}" 
        state: present
