---
- hosts: armpit
  remote_user: root
  vars:
    mongodbrepodef: |
      [mongodb]
      name=MongoDB repo
      baseurl=http://downloads-distro.mongodb.org/repo/redhat/os/x86_64/
      gpgcheck=0
      enabled=1
  tasks:
    - name: Ensure EPEL is installed
      yum: name=epel-release state=latest
    - name: Ensure nodejs is installed
      yum: name=nodejs state=latest
    - name: Ensure npm is installed
      yum: name=npm state=latest
    - name: Ensure php is installed
      yum: name=php state=latest
    - name: Ensure php-mysql is installed
      yum: name=php-mysql state=latest
    - name: Ensure php-fpm is installed
      yum: name=php-fpm state=latest
    - name: Add Mongodb repository
      copy: content="{{ mongodbrepodef }}" dest=/etc/yum.repos.d/mongodb.repo
    - name: Ensure mongodb-org is installed
      yum: name=mongodb-org state=latest
    - name: Ensure mongodb-org-server is installed
      yum: name=mongodb-org-server state=latest
    - name: Ensure mongod is enabled and started
      service: name=mongod enabled=yes state=started
    - name: Ensure php-pecl-mongo is installed
      yum: name=php-pecl-mongo state=latest

# - name: install nginx rpm from a local file
#   yum: name=/usr/local/src/nginx-release-centos-6-0.el6.ngx.noarch.rpm state=present