#!/usr/bin/env php
<?php

// set to run indefinitely if needed
set_time_limit(0);

/* Optional. It’s better to do it in the php.ini file */
date_default_timezone_set('America/Los_Angeles'); 

/* Use 128M memory it may need */
ini_set('memory_limit', '128M');

// include the composer autoloader
require_once __DIR__ . '/../vendor/autoload.php'; 

// import the Symfony Console Application 
use Symfony\Component\Console\Application; 
use USF\IdM\ImportAccountsCommand;
use USF\IdM\ImportRolesCommand;
use USF\IdM\ImportAccountRolesCommand;
use USF\IdM\DeleteAccountCommand;
use USF\IdM\DeleteRoleCommand;
use USF\IdM\DumpArmCommand;
use USF\IdM\RestoreArmCommand;

$app = new Application();
$app->add(new ImportAccountsCommand());
$app->add(new ImportRolesCommand());
$app->add(new ImportAccountRolesCommand());
$app->add(new DeleteAccountCommand());
$app->add(new DeleteRoleCommand());
$app->add(new DumpArmCommand());
$app->add(new RestoreArmCommand());
$app->run();
?>